Currently, the test_hafnian_approx.py tests sometimes randomly fail.
This is specific to the test_rank_one function which calls haf_real with approx=True, which in turn calls the C++ function hafnian_nonneg in libwalrus. hafnian_nonneg uses the std::default_random_engine generator (with no seed) causing the output to be random.
Fix
Mark the specific test as flaky (e.g. with https://github.com/box/flaky).
This could also be solved by passing a random seed value to hafnian_nonneq in libwalrus, although this means changing quite a few functions along the way (and might not be worth it).
