I have been trying to execute examples like Entangle by IBM, but failed to do so.
However it is possible to execute quantum_random_numbers_ibm.py provided my username and password.
ibm.py and ibm_entangle.ipynb aren't working.

Is this got to do with IBM QE itself or a bug in backend code?
Since you can run the qrng example, it is very unlikely that it's a bug in the backend code. Currently, there seems to be a long queue which keeps me from reproducing this, so I will try again tomorrow.
In any case: Could you scroll down all the way and tell me what exception you see?
By the way: Did you add use_hardware=True in the quantum RNG example? If not, it defaults to using the IBM simulator which would explain why this worked but entangle didn't (as that one uses the quantum device by default).
@thomashaener , Yeah. use_hardware=True isn't used in RNG. I will check that out.
Error message :
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/backends/_ibm/_ibm.py", line 214, in _run
data = res['data']['p']
TypeError: 'NoneType' object is not subscriptable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "ibm.py", line 44, in 
print(run_entangle(eng))
File "ibm.py", line 28, in run_entangle
eng.flush()
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_main.py", line 242, in flush
self.receive([Command(self, FlushGate(), ([WeakQubitRef(self, -1)],))])
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_main.py", line 226, in receive
self.send(command_list)
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_basics.py", line 186, in send
self.next_engine.receive(command_list)
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_tagremover.py", line 58, in receive
self.send([cmd])
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_basics.py", line 186, in send
self.next_engine.receive(command_list)
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_optimize.py", line 237, in receive
self.send([cmd])
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_basics.py", line 186, in send
self.next_engine.receive(command_list)
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_replacer/_replacer.py", line 216, in receive
self.send([cmd])
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_basics.py", line 186, in send
self.next_engine.receive(command_list)
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_tagremover.py", line 58, in receive
self.send([cmd])
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_basics.py", line 186, in send
self.next_engine.receive(command_list)
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_ibmcnotmapper.py", line 272, in receive
self._run()
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_ibmcnotmapper.py", line 202, in _run
self.next_engine.receive([cmd])
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_optimize.py", line 237, in receive
self.send([cmd])
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/cengines/_basics.py", line 186, in send
self.next_engine.receive(command_list)
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/backends/_ibm/_ibm.py", line 258, in receive
self._run()
File "/Users/sb/.local/lib/python3.6/site-packages/projectq/backends/_ibm/_ibm.py", line 244, in run
raise Exception("Failed to run the circuit. Aborting.")
Exception: Failed to run the circuit. Aborting.
That's the error message.
Thanks! I think I found the problem. There's a PR waiting to be accepted (which will happen once ibmqx2 is online again).
Sure, thank you! üëç
Sure, thanks for pointing out that it wasn't working!
I have added support for both 5-qubit chips so you can now choose which one to use (see ibm.py and the jupyter notebook for examples). Currently, ibmqx4 is online but ibmqx2 is still offline.
However, it will probably still not work as the queue is way too long. Once your job is complete, you will find the results in your IBM QE account, though :-)
