Not sure if the API allows this but we've wasted many hours with strange behaviour that we eventually track down to an unlocked LabBrick.
Bump! Caused hours of grief yet again....
Closed by 8d5383a
LabBrick gets unlocked between the check and the time the experiment starts. The error is therefore caught too late. After check and error message, the lock gets fixed again.
In other words, for consecutive experiments: 1) locked; 2) locked ... N) unlocked ERROR/WARNING at the beginning of N+1; N+1) locked ...
Maybe we could recheck after setAll.  That's the last point we touch this.
