Since merging PR #1082 , I've been getting this strange error whenever I import QuTiP:
The codes however run fine. Here's the output from my qutip.about()
@nathanshammah ran this on his Mac, and had the following results.
The file runs fine on his Mac with
The file throws an error when:
Error message (then the code runs anyway):
His qutip.about():
Notice that in his case OPEN MP seems installed.
@Ericgig could you please take a look at this? CCing @nathanshammah again.
Hi @tehruhn, I also have the error but it does not appear when using jupyter so I missed it. The error comes from a line inside a try block, so I am not sure why it is not properly suppressed... I did touch much in that area so it should be a simple fix.
