Pytests run on Windows machines via Azure Pipelines fail on all tested Python versions with
Windows fatal exception: access violation - Cmd.exe exited with code '-1073741819'.
Whenever specified, the file associated with the error is threading.py.
Error output gets garbled; may suggest serious problems with memory management, pointers, etc.
All the same pytests (nominally) pass on Azure Pipelines Linux and MacOS machines.
The problem is not observed when running pytests on a local windows machine.
Ruled out possibilities:
Pytest now pass again on Azure / windows.
