ModuleNotFoundError                       Traceback (most recent call last)
 in ()
----> 1 from qutip import *
2 about()
~\qutip_init_.py in ()
37
38 import qutip.settings
---> 39 import qutip.version
40 from qutip.version import version as version
41 from qutip.utilities import _version2int
ModuleNotFoundError: No module named 'qutip.version'
It seems to miss a file which is 'qutip/version.py.'
Hi, could you please tell us how you installed QuTiP and which python are you using? Just type the following in the terminal
To check how QuTiP was installed (if on Linux or Mac):
If on windows, download Anaconda and install QuTiP from conda-forge with
Thank you for your prompt reply.
@sahmed95
QuTip was installed on Windows
We download anaconda and install QuTip from conda-forge with
but when run
the following message occurred:
@ajgpitch
Thank you for your suggestion:)
@heathcliffYang This seems to be running okay. I hope you can use QuTiP now. Try running this simple code in python.
P.S. you may also want to update your Anaconda as the latest is Anaconda 5. Let me know if you have any other issues.
Tried to install Qutip in windows 10, but showing following errors while working
.
.
.
.....
U = propagator(H,1, unitary_mode='single')
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\propagator.py", line 164, in propagator
_safe_mode=False)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 185, in sesolve
progress_bar)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 520, in _sesolve_list_str_td
exec(code, globals())
File "", line 1, in 
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 462, in load_module
language_level=self.language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
raise exc.with_traceback(tb)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
ImportError: Building module rhs278046 failed: ['distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat\n']
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
self.test(*self.arg)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_rhs_reuse.py", line 53, in test_rhs_reuse
out1 = qt.mesolve(H, psi0,tlist, e_ops=e_ops)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\mesolve.py", line 336, in mesolve
e_ops, args, options, progress_bar)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 520, in _sesolve_list_str_td
exec(code, globals())
File "", line 1, in 
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 462, in load_module
language_level=self.language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
raise exc.with_traceback(tb)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
ImportError: Building module rhs278047 failed: ['distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat\n']
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
self.test(*self.arg)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_sesolve.py", line 190, in test_04_1_state_with_list_str_H
td_args=td_args)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_sesolve.py", line 64, in check_evolution
args=td_args)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 185, in sesolve
progress_bar)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 520, in _sesolve_list_str_td
exec(code, globals())
File "", line 1, in 
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 462, in load_module
language_level=self.language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
raise exc.with_traceback(tb)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
ImportError: Building module rhs278048 failed: ['distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat\n']
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
self.test(*self.arg)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_sesolve.py", line 207, in test_04_2_unitary_with_list_func_H
td_args=td_args)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_sesolve.py", line 67, in check_evolution
output = sesolve(H, U0, tlist, args=td_args)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 185, in sesolve
progress_bar)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 520, in _sesolve_list_str_td
exec(code, globals())
File "", line 1, in 
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 462, in load_module
language_level=self.language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
raise exc.with_traceback(tb)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
ImportError: Building module rhs278049 failed: ['distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat\n']
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
self.test(*self.arg)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_sesolve.py", line 226, in test_05_1_state_with_interp_H
td_args=td_args)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_sesolve.py", line 64, in check_evolution
args=td_args)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 185, in sesolve
progress_bar)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 520, in _sesolve_list_str_td
exec(code, globals())
File "", line 1, in 
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 462, in load_module
language_level=self.language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
raise exc.with_traceback(tb)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
ImportError: Building module rhs278050 failed: ['distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat\n']
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
self.test(*self.arg)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_sesolve.py", line 245, in test_05_2_unitary_with_interp_H
td_args=td_args)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_sesolve.py", line 67, in check_evolution
output = sesolve(H, U0, tlist, args=td_args)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 185, in sesolve
progress_bar)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 520, in _sesolve_list_str_td
exec(code, globals())
File "", line 1, in 
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 462, in load_module
language_level=self.language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
raise exc.with_traceback(tb)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
ImportError: Building module rhs278051 failed: ['distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat\n']
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
self.test(*self.arg)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_sesolve.py", line 354, in test_06_4_compare_state_and_unitary_list_str
normalize=False, td_args=td_args, tol=5e-5)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_sesolve.py", line 255, in compare_evolution
options=options,args=td_args)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 185, in sesolve
progress_bar)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\sesolve.py", line 520, in _sesolve_list_str_td
exec(code, globals())
File "", line 1, in 
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 462, in load_module
language_level=self.language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
raise exc.with_traceback(tb)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
inplace=build_inplace, language_level=language_level)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
reload_support=pyxargs.reload_support)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
dist.run_commands()
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
self.build_extension(ext)
File "C:\Users\MTS-144\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 345, in compile
self.initialize()
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 238, in initialize
vc_env = _get_vc_env(plat_spec)
File "C:\Users\MTS-144\Anaconda3\lib\distutils_msvccompiler.py", line 134, in _get_vc_env
raise DistutilsPlatformError("Unable to find vcvarsall.bat")
ImportError: Building module rhs278052 failed: ['distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat\n']
Traceback (most recent call last):
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
self.test(*self.arg)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\tests\test_steadystate.py", line 490, in test_driven_cavity_power_gmres
use_precond=1)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\steadystate.py", line 306, in steadystate
return _steadystate_power(A, ss_args)
File "C:\Users\MTS-144\Anaconda3\lib\site-packages\qutip\steadystate.py", line 938, in _steadystate_power
check))
Exception: power-gmres failed to find solution in 1000 iterations.
Ran 564 tests in 898.617s
FAILED (SKIP=9, errors=57)
For example.. one of the errors ...
Qobj([1,2,3,4,5])
C:\Users\MTS-144\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:448: DeprecationWarning: input_splitter is deprecated since IPython 7.0, prefer input_transformer_manager.
status, indent_spaces = self.shell.input_splitter.check_complete(code)
Traceback (most recent call last):
File "", line 1, in 
Qobj([1,2,3,4,5])
NameError: name 'Qobj' is not defined
@manas7891 This is a question about usage of qutip. Please ask on help group and include full code snippet.
https://groups.google.com/forum/#!forum/qutip
You get the test errors because you don't have working C++ compiler
Hi, could you please tell us how you installed QuTiP and which python are you using? Just type the following in the terminal
To check how QuTiP was installed (if on Linux or Mac):
If on windows, download Anaconda and install QuTiP from conda-forge with
I created an environment for qutip and then used the following code
conda install -c conda-forge qutip. I'm still seeing this error ModuleNotFoundError: No module named 'qutip'
